name: Code Review
on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read
  packages: read

jobs:
  code-review:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Code Review"
        uses: CI-T-HyperX/flow-actions/pull-request-review@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
